Make implementation of sprint 10
StanislavFishkov/java-filmorate pull request #5
Opened 2024-06-20 21:47 UTC by StanislavFishkov

2024-06-21 19:14 UTC, z8q requested changes

2024-06-21 19:14 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail() == null || user.getEmail().isBlank() || !user.getEmail().contains("@")) {
В классе User над полем email есть валидационная аннотация, можно попробовать убрать проверки здесь.

`@Email` только допускает null значения, чтобы было соответствие с проверками в этом if, 
в классе User надо написать так
```JAVA
@NotNull
@Email
private String email;
```

2024-06-21 19:14 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail() == null || user.getEmail().isBlank() || !user.getEmail().contains("@")) {
В полях, где простые проверки, можно попробовать тоже аннотации применить. Как пример:
`@NotNull`, `@NotBlank`, `@Size`, `@Past`

2024-06-21 19:14 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int getNextId() {
С ростом числа записей будет повышаться сложность расчета id. Можно просто счетчик сделать и увеличивать

2024-06-21 19:14 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin() == null || user.getLogin().isBlank() || user.getLogin().contains(" ")) {
.isBlank() проверяет пустая ли строка и состоит ли из пробелов, в третью проверку `user.getLogin().contains(" ")` не попадем

2024-06-21 19:19 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin() == null || user.getLogin().isBlank() || user.getLogin().contains(" ")) {
А если пробел в середине, например вот так:"test test", то ведь isBlank этого не отловит, а contains(" ") поймает. Я так это понял требование "логин **не может** быть пустым и **содержать пробелы**;". Пока contains(" ") не добавил у меня unit-тест давал сделать логин с пробелом внутри.

2024-06-21 19:22 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail() == null || user.getEmail().isBlank() || !user.getEmail().contains("@")) {
Я валидационную анотацию сделал для примера из доп. задания, но она ведь не выкидывает нашего исключения "ValidationException", а также в логи не пишет. Как сделать так, чтобы проверка была аннотациями, но выкидывалась наш кастомный exception и в лог шла запись?

2024-06-21 19:24 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int getNextId() {
Я это взял из котограмма, который был сквозным примером в теории - подумал, что так принято) Исправлю.

2024-06-25 19:35 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail() == null || user.getEmail().isBlank() || !user.getEmail().contains("@")) {
Посмотрел темы следующего спринта: там и обработка ошибок и логирование в приложениях на Spring! Реализую это в следующем ТЗ похоже)

2024-06-26 18:08 UTC, z8q approved these changes

2024-06-29 13:01 UTC, merged