Sprint 12. Add database
StanislavFishkov/java-filmorate pull request #7
Opened 2024-07-27 22:20 UTC by StanislavFishkov

2024-07-28 21:01 UTC, z8q requested changes

2024-07-28 23:23 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +package ru.yandex.practicum.filmorate.controller;
Да, согласен, убрал. Сам думал, что это лишнее, но нужно было подтверждение)

2024-07-28 23:28 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/JdbcFilmRepository.java
> +        String sqlQuery = "SELECT f.*, mpa.\"name\" AS mpa_rating_name, genre.\"genre_id\", " +
В пачке было обсуждение поля rate даже - https://app.pachca.com/chats/7946299?message=294189694. 
Я так понял, что она не используется в этом задании:
"Vladimir Ivanov [Старший наставник]
12:17
Поле rate не используется, тест проверяет что оно игнорирутся"

А разве запрос Count() по проиндексированному полю является дорогой операцией? Стоит ли вносить денормализацию тут? Мне кажется, что не обязательно. Пока делать не стал.

2024-07-28 23:30 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/JdbcUserRepository.java
> +    public User create(User user) {
Тоже было обсуждение в пачке: https://app.pachca.com/chats/7946299?message=291119220
Владимир написал, что это задача из будущих спринтов:
"Vladimir Ivanov [Старший наставник]
09:04
В проекте фильморейт не нужно проверять на уникальность
Возможно ревьюер перепутал задания (у нас будет в следующем модуле в новом проекте)
Итого делать не нужно"

Но тут я решил сделать, так как это логично. Так как у меня все контроли на уровне сервиса, добавил проверку в имплементации интерфейса UserService.

2024-07-28 23:32 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/JdbcUserRepository.java
> +    public void addFriend(Long userId, Long friendId) {
Исправил. Также на уровне сервиса сделал проверку.

Кстати, а есть какие-то устоявшиеся правила по разнесению проверок между сервисом и ремозиторием? Если есть ссылка, где можно почитать про best practices по этому поводу, буду благодарен.

2024-07-28 23:33 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private final Set<Long> friends = new HashSet<>();
Установил @JsonIgnore, спасибо.

2024-07-29 18:21 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/JdbcUserRepository.java
> +    public void addFriend(Long userId, Long friendId) {
В репозитории можно описывать команды для чтения и записи.
Проверки и логику лучше производить в сервисном слое.
В последующих домашках будет возможность реализовать решения с использованием [JpaRepository](https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html)
в интерфейсах будет описываться только запрос, без логики и проверок

2024-08-26 23:50 UTC, merged